# ==========================================
#  Generals and Performance
# ==========================================
set -g mouse on
set -s escape-time 0
set -g history-limit 50000          
set -g display-time 4000            
set -g status-interval 5            
set -g focus-events on              

# Terminal & True Color desteği
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-overrides ",$TERM:Tc" 

# Panes & Indexes
set -s set-clipboard on
set -g base-index 1                 
setw -g pane-base-index 1           
set -g renumber-windows on          

# Prefix settings
unbind C-b
set -g prefix C-w
bind C-w send-prefix

# ==========================================
# Config Reload
# ==========================================
bind r source-file ~/.config/tmux/tmux.conf \; 

# ==========================================
# Pane split
# ==========================================
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ==========================================
# Kakoune copy mode 
# ==========================================
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ==========================================
# Themes and colors
# ==========================================
set -g status-position top

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

set -g status-style "bg=#{E:@catppuccin_status_background}"



source-file -q "$HOME/.config/tmux/themes/noctalia.conf"
