#----------------------My own Comforts--------------------------
#line numbers
add-highlighter global/ number-lines
# tmux title pane is so crowded without it. 
set-option global ui_options terminal_set_title=no

map global user -docstring 'open fuzzy finder' f ': edit %sh{fzf-tmux --color=16 --preview "bat --theme=Coldark-Dark --style=numbers,changes --color always {}" -}<ret>'

# I dont want to add highlighter every time when I open a ".conf*" file 
hook global BufOpenFile .*\.conf %{
    set-option buffer filetype ini
}

hook global WinSetOption filetype=config %{
    add-highlighter window/config regex \
        "#.*$" 0:comment \
        "^[A-Za-z0-9_-]+(?=\\s*=)" 0:keyword \
        "=.*$" 0:string
}


#------------------------Plugin Manager--------------------------------
# Here, I m using bundle-kak plugin for plugin manager
#
#-----------------Load Bundle--------------------------------------
source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

#------------------Powerline------------------------------------
bundle powerline https://github.com/andreyorst/powerline.kak %{
    powerline-theme palenight
    powerline-start
}

#------------------Cosmetics--------------------------------------------
#Catppuccin deposunu indir ve mocha temasını aktif et
bundle-theme catpuccin https://github.com/catppuccin/kakoune
colorscheme catppuccin_macchiato




#------------------LSP--------------------------------------------
bundle kak-lsp https://github.com/kak-lsp/kak-lsp %{
lsp-inlay-hints-enable global
lsp-inlay-diagnostics-enable global

set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"
# set-option global modelinefmt "%opt{lsp_modeline}"


map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'
map global goto y <esc>:lsp-type-definition<ret> -docstring 'LSP type definition'

# map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP errors'

hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
  lsp-enable-window
}


hook global WinSetOption filetype=(c|cpp) %{
    set-option window formatcmd 'clang-format'
    set-option window lsp_auto_highlight_references true
    hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
    hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
    hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
    hook -once -always window WinSetOption filetype=.* %{
        remove-hooks window semantic-tokens
    }
}


hook global InsertCompletionHide .* %{
    unmap window insert <tab>
    unmap window insert <s-tab>
}
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}

}

bundle-install-hook kak-lsp %{
   # Check if the binary does NOT exist (! -f)
    if [ ! -f "$HOME/.cargo/bin/kak-lsp" ]; then
        echo "Binary not found, installing kak-lsp..."
        cargo install --locked --force --path .
    else
        echo "kak-lsp binary already exists, skipping installation."
    fi
}

#---------------Focus---------------------------------------------------
bundle focus https://github.com/caksoylar/kakoune-focus %{

map global user <space> ': focus-toggle<ret>' -docstring "toggle selections focus"

}

#--------------Buffers--------------------------------------------------
bundle kak-buffers  https://github.com/Delapouite/kakoune-buffers %{
    # Eklenti yüklendiğinde otomatik olarak kısayolları tanımlayalım

    #------------------Debug
    # # Space + b tuşuna basınca açık buffer'ların listesini (info box) sağda gösterir
    # map global user b ': info-buffers<ret>' -docstring 'açık bufferları listele'
    
    # # Space + n ile sonraki buffer'a geç
    # map global user n ': buffer-next<ret>' -docstring 'sonraki buffer'
    
    # # Space + p ile önceki buffer'a geç
    # map global user p ': buffer-prev<ret>' -docstring 'önceki buffer'


  map global normal ^ q
  map global normal <a-^> Q
  map global normal q b
  map global normal Q B
  map global normal <a-q> <a-b>
  map global normal <a-Q> <a-B>
  map global user b ': enter-buffers-mode<ret>' -docstring 'buffers'
  map global user B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)'
}


#------------------Smooth Scrols---------------------------------------------
bundle smooth-scroll  https://github.com/caksoylar/kakoune-smooth-scroll  %{
    hook global WinCreate [^*].* %{
        hook -once window WinDisplay .* %{
            smooth-scroll-enable
        }
    }    

    # Standart Kakoune hareket kısayollarını yumuşak kaydırma ile değiştir
    map global normal <c-f> ': smooth-scroll-move page-down<ret>' -docstring 'Sayfa aşağı (yumuşak)'
    map global normal <c-b> ': smooth-scroll-move page-up<ret>'   -docstring 'Sayfa yukarı (yumuşak)'
    map global normal <c-d> ': smooth-scroll-move half-down<ret>' -docstring 'Yarım sayfa aşağı (yumuşak)'
    map global normal <c-u> ': smooth-scroll-move half-up<ret>'   -docstring 'Yarım sayfa yukarı (yumuşak)'

    # Some options
    # set-option global smooth_scroll_interval 10
    # set-option global smooth_scroll_speed 3
}

#------------------Clipboard----------------------------------------------
bundle kakboard https://github.com/lePerdu/kakboard %{
hook global WinCreate .* %{ kakboard-enable }
}

#-------------------Paranthesis Pairs-------------------------------------
bundle auto-pairs https://github.com/alexherbo2/auto-pairs.kak %{
    enable-auto-pairs
}

#-------------------Filetree-----------------------------------
bundle kakfiletree https://github.com/westra126/kakfiletree %{
set-option global kakfiletree_width "25"   # split width in columns
}
bundle-install-hook kakfiletree %{
  cargo build --release
}

#------------------Pop-up--------------------------------------

bundle popup https://github.com/enricozb/popup.kak %{
evaluate-commands %sh{kak-popup init}
}

bundle-install-hook popup %{
cargo install kak-popup
}

#-----------------Splash Screen--------------------------------
bundle splash 'https://github.com/Hjagu09/splash.kak'





bundle-install-hook giallo-kak %{
   # Check if the binary does NOT exist (! -f)
    if [ ! -f "$HOME/.cargo/bin/giallo-kak" ]; then
        echo "Binary not found, installing kak-lsp..."
        cargo install --locked --force --path .
    else
        echo "kak-lsp binary already exists, skipping installation."
    fi
}



#===================================================
# 		Giallo Package
#==================================================

bundle giallo-kak https://github.com/yukaii/giallo.kak %{
    evaluate-commands %sh{giallo-kak init}
}


bundle-install-hook giallo-kak %{
    if [ ! -f "$HOME/.cargo/bin/giallo-kak" ]; then
        echo "Binary not found, installing giallo-kak..."
        cargo install giallo-kak --locked
    else
        echo "giallo-kak binary already exists, skipping installation."
    fi
}



