# ~/.config/foot/foot.ini

shell=/usr/bin/fish
# Terminal genel ayarları
term = foot
initial-window-size-chars = 110x30
title = foot
app-id = foot

# Font Ayarları: Fantasque Sans Mono
# NOT: Simge/Icon desteği için FantasqueSansM Nerd Font tercih edilmiştir.
font = FantasqueSansM Nerd Font:size=16, Noto Color Emoji:size=14
font-bold = FantasqueSansM Nerd Font:style=Bold:size=16
font-italic = FantasqueSansM Nerd Font:style=Italic:size=16
font-bold-italic = FantasqueSansM Nerd Font:style=Bold Italic:size=16

# Window padding (İç boşluklar)
pad =  0x0

# Theme:
include = ~/.config/foot/themes/noctalia

[scrollback]
lines = 100000
multiplier = 3.0

[cursor]
style = block
blink = yes

[mouse]
hide-when-typing = yes

[url]
launch = xdg-open ${url}
osc8-underline = always

[key-bindings]
scrollback-up-page = Shift+Page_Up
scrollback-down-page = Shift+Page_Down
clipboard-copy = Control+Shift+c XF86Copy
clipboard-paste = Control+Shift+v XF86Paste
font-increase = Control+plus Control+equal
font-decrease = Control+minus
font-reset = Control+0
