#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='catppuccin-mocha-blue-standard+default'
ICONS='Breeze-Dark'
FONT='JetBrainsMono Nerd Regular 10'
CURSOR='Material Cursors'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
